### ISSUE TITLE
Test and maybe implement New save system.

### ISSUE THREAD

**Issue by Frosties82** [Frosties82/RedSnow#44]

**Comment by thebgpikester** [comment]
Brainstorming on negatives in implementing
1. The existing CTLD Save mechanism would need to go off
2. It's possibly going to keep too much over time, does it need a method to delete units?
3. The capture bases methods after start wont be required (no spawning in new stuff on capture)
4. Any fckup in the file and it's good night sister :) Backups?
5. Anything that could happen in the first second of the miz that would be upset by seeing two completely different picture?

Can't think of anything else yet.

**Comment by Frosties82** [comment]
New save system seems to be going well. Will close this issue.
