### ISSUE TITLE
Base the mapmarkers at beginning on ZONE instead of STATIC

### ISSUE THREAD

**Issue by Frosties82** [Frosties82/RedSnow#57]
At the beginning of the mission, the system checks a file on wich statics are alive or not, then based on this it create mapmarkers on the position with the EXACT LL DMS coordinates. 
This makes it very easy to check the map, load the coordinates in a JDAM and off you go.

Proposal:
Add a zone on each STATIC target, a bit offset in any direction.
This zones center will act as the center for coordinates, and thus the static coordinates will be hidden. This will force the player on two paths:
1 - Recon the area beforehand, to get precise coordinates (hopefully)
2 - The player will use dumb bombs or GBUs.

Thoughts?

**Comment by thebgpikester** [comment]
My cup of tea is getting cold.
And
Yes I have a Marker script in existence that uses zones.

The only thing to consider is a Zone prefix in order to use a SET and thus get all zones and iterate in one loop, rather than declaring them out long hand. 

My question is, what is the impact of changing every zone that refers to an airbase to a prefixed one? like Kutaisi changes to x_Kutaisi?

**Comment by Frosties82** [comment]
To my knowledge, the zones are only used for the mapmarkers, so we have to adjust accordingly, but i dont see that as a problem really?

**Comment by thebgpikester** [comment]
in the future when moving to zone based campaigns (which i'm actually already close to) Zones and their names will be a key feature. at least the round zones will, wonky poly zones will be their own thing.

I'm trying to manage a flow to move this way so it will cause the least issues in converting. I'm just getting up to speed on the existing code again really.

If the zones aroeund the Airbases are just for markers then the simplest method by far is a SET_ZONE and a CONVERSION of this to work for current Red Snow

```SCHEDULER:New( nil, function()
--DO NOT CHANGE THE OUTPUT TEXT AS IT IS USED EXACTLY!!!
SetZone:ForEachZone(function(zone) --FAULTY! can return nothing soemtimes.
local _blu = countBlue (zone )
local _red = countRed (zone )
local _name = zone:GetName()
local _currentState = coaZones[_name]
  if _blu > 0 and _red == 0 then
    coaZones[zone:GetName()]="Coalition owned" --dont change this
      if _currentState ~= "Coalition owned" then blueCapture(_name) end --Triggers on change. Compare it to previous table entry and if different launch function
 
  elseif _blu == 0 and _red > 0 then 
    coaZones[zone:GetName()]="Russian owned"--dont change this
      if _currentState ~= "Russian owned" then redCapture(_name) end
 
  elseif _blu == 0 and _red == 0 then
    coaZones[zone:GetName()]="Empty"--dont change this
      if _currentState ~= "Empty" then empty(_name) end
 
  elseif _blu > 0 and _red > 0 then
    coaZones[zone:GetName()]="contested"--dont change this
      if _currentState ~= "contested" then contested(_name) end
  end
end)
--s(coaZones)--debug
--REMOVE OLD MARKS ON MAP
for k,v in pairs (markID) do
local pos = ZONE:FindByName(k):GetCoordinate()
pos:RemoveMark(v) --remove current mark
end
markID={}--flatten table
--PUT NEW MARKS ON
for k,v in pairs (coaZones) do
local pos = ZONE:FindByName(k):GetCoordinate()
local DMS = pos:ToStringLLDMS()
local _MarkID = pos:MarkToAll(k .. " is currently " .. v .. ". \n".. DMS, true )
markID[k]=_MarkID --add a new entry in a table of the mark iD
end 

end,
{}, 2, 30 )```
